### ISSUE TITLE
  TypeError: os.tmpDir is not a function

### ISSUE THREAD

**Issue by vivitali** [GaryChangCN/koa2-formidable#3]
hi, got an error
  TypeError: os.tmpDir is not a function
      at new IncomingForm (C:\service\node_modules\formidable\lib\incoming_form.js:29:41)
      at C:\service\node_modules\koa2-formidable\index.js:7:22
      at dispatch (C:\service\node_modules\koa-compose\index.js:44:32)
      at C:\service\node_modules\koa-compose\index.js:36:12
      at Server.handleRequest (C:\service\node_modules\koa\lib\application.js:137:7)
      at Server.emit (events.js:315:20)
      at parserOnIncoming (_http_server.js:874:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)

(node:24588) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by GaryChangCN** [comment]
it's formidable bug [#276](https://github.com/node-formidable/formidable/issues/276)

```
yarn remove koa2-formidable && yarn add koa2-formidable
```

make sure formidable version > 2.0.0

**Comment by vivitali** [comment]
I believe you have formidable version in your package defined as     "formidable": "^1.0.17"
That means I can't update it from my side up to 2
![image](https://user-images.githubusercontent.com/12481114/113262312-228a9c80-92d9-11eb-9758-dcf2f88995db.png)

**Comment by GaryChangCN** [comment]
fix in https://github.com/GaryChangCN/koa2-formidable/commit/0854759d90ba7e0c80664b6cd1d30da42d3d321c

npm i koa2-formidable@^1.2.2
